---
- name: Create registry data directory
  file:
    path: "{{ registry_local_storage_path }}"
    state: directory
    mode: 0777
  become: yes

- name: Create config dir
  file:
    path: "{{ registry_conf_dir }}"
    state: directory
    mode: 0755
  become: yes

- name: Put registry ymls
  template:
    src: "{{ item }}.j2"
    dest: "{{ registry_conf_dir }}/{{ item }}"
  with_items:
    - registry-rc.yml
    - registry-svc.yml
  become: yes

- name: Apply registry ymls
  kubectl:
    action: apply
    filepath: "{{ registry_conf_dir }}/{{ item }}"
  environment:
    KUBECONFIG: "{{ kubectl_conf_path }}"
  with_items:
    - registry-rc.yml
    - registry-svc.yml
  become: yes
