---
- name: Add kubernetes' official GPG key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  become: yes

- name: Set up kubernetes repository
  apt_repository:
    repo: "{{ kube_repo }}"
    state: present
  become: yes

- name: Install kubelet, kubeadm, kubectl
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: present
  with_items:
    - kubelet
    - kubeadm
    - kubectl
  become: yes

  # https://github.com/kubernetes/kubernetes/issues/53333
- name: disable kubelet fail-swap-on
  lineinfile:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    state: present
    line: 'Environment="KUBELET_EXTRA_ARGS=--fail-swap-on=false"'
    insertafter: '^\[Service\]'
  become: yes
  notify: restart kubectl
