---
- hosts: all
  roles:
    - common

- hosts: kube-master
  roles:
    - kube-master
    - weave

- hosts: kube-node
  roles:
    - kube-node

- hosts: kube-registry
  run_once: yes
  roles:
    - registry

- hosts: kube-master
  run_once: yes
  roles:
    - fn
