---
- name: Reload systemd
  command: systemctl daemon-reload
  become: yes

- name: Restart docker
  service: name=docker state=restarted
  become: yes

- name: Reload grub
  command: update-grub
  become: yes
