---
- name: Check if already installed
  stat:
    path: /etc/kubernetes/pki
  register: ca

- block:
    - meta: flush_handlers
    # workaround for https://github.com/kubernetes/kubernetes/issues/53356
    - name: stop kubelet
      systemd: name=kubelet state=stopped
      become: yes

    - name: remove kubelet conf
      file:
        path: /var/lib/kubelet/pki
        state: absent
      become: yes

    - name: kubeadam join
      shell: >
        kubeadm join
        --token={{ kubeadm_token }}
        {{ kube_master_host }}:{{ kube_master_api_port }}
      become: yes
      register: output

    - debug: msg={{ output.stdout_lines }}
  when: ca.stat.isdir is not defined
