---
- name: kubectl version
  shell: kubectl version | base64 | tr -d '\n'
  register: kubeversion

- name: Download weave manifest
  get_url:
    url: "https://cloud.weave.works/k8s/net?k8s-version={{ kubeversion.stdout }}"
    dest: "{{ weave_manifest_path }}"
    mode: 0600
  become: yes

- name: Setup weave pod
  command: kubectl apply -f {{ weave_manifest_path }}
  environment:
    KUBECONFIG: "{{ kubectl_conf_path }}"
  become: yes
