---
- name: Create config dir
  file:
    path: "{{ fn_conf_dir }}"
    state: directory
    mode: 0755
  become: yes

- name: Put svc yml
  template:
    src: "fn-svc.yml.j2"
    dest: "{{ fn_conf_dir }}/fn-svc.yml"
  become: yes

- name: Apply svc yml
  command: kubectl apply -f {{ fn_conf_dir }}/fn-svc.yml
  environment:
    KUBECONFIG: "{{ kubectl_conf_path }}"
  become: yes

- name: Put resource file
  delegate_to: localhost
  copy:
    content: |
      export API_URL=http://{{ ansible_host }}:{{ fn_port }}
      export FN_REGISTRY=rerorero
      export FN_APP_NAME=test
    dest: "{{ playbook_dir }}/functions/setup.sh"
    mode: 0755
